// src/app/pages/team-generator/team-generator.component.ts
import {Component} from '@angular/core';
import {FormsModule} from "@angular/forms";

@Component({
  selector: 'app-team-generator',
  standalone: true,
  imports: [
    FormsModule
  ],
  templateUrl: './team-generator.component.html',
  styleUrl: './team-generator.component.scss'
})
export class TeamGeneratorComponent {

  names: string[] = [];
  nameToAdd: string = "";
  teamCount = 2;
  teams: string[][] = [];

  addName() {
    if (this.nameToAdd.length > 0) {
      this.names.push(this.nameToAdd);
      this.nameToAdd = "";
    }
  }

  deleteName(i: number) {
    this.names.splice(i, 1);
  }

  generateTeams() {
    const k = this.teamCount < this.names.length ? this.teamCount : this.names.length
    const array = this.shuffleArray(this.names);
    this.teams = this.splitArray(array, k);
  }

  splitArray(array: any[], k: number) {
    const partSize = Math.floor(array.length / k);
    const extra = array.length % k;
    const result = [];

    let start = 0;
    let end = 0;

    for (let i = 0; i < k; i++) {
      end = start + partSize + (i < extra ? 1 : 0);
      result.push(array.slice(start, end));
      start = end;
    }

    return result;
  }

  shuffleArray(array: any[]) {
    const shuffledArray = [...array]; // Create a shallow copy to avoid modifying the original array
    return shuffledArray.sort(() => Math.random() - 0.5);
  }
}

<div class="container">
  <h1>Random teams generator</h1>
  <div class="row">
    <div class="col">
      <div class="row">
        <h2>Names</h2>
        @for (name of names; track $index) {
          <div class="my-1">
            {{ name }}
            <button class="btn btn-outline-secondary" (click)="deleteName($index)">
              <i class="bi bi-trash"> </i>
            </button>
          </div>
        }
      </div>

      <div class="row my-1">
        <div class="col-auto">
          <input class="form-control" [(ngModel)]="nameToAdd" type="text">
        </div>
        <div class="col-auto">
          <button class="btn btn-secondary" [disabled]="nameToAdd.length===0" (click)="addName()">Add Name</button>
        </div>
      </div>

      <div class="row my-1">
        <div class="col-2">
          <input class="form-control" [(ngModel)]="teamCount" type="number">
        </div>
        <div class="col-auto">
          <button class="btn btn-secondary" [disabled]="names.length===0" (click)="generateTeams()">Generate Teams
          </button>
        </div>
      </div>
    </div>

    <div class="col">
      <h2>Teams</h2>
      @for (team of teams; track $index) {
        <h3>Team {{ $index + 1 }}</h3>
        @for (name of team; track $index) {
          <div>{{ name }}</div>
        }
      }
    </div>
  </div>
</div>

// src/pages/TeamGenerator.tsx
import {useState} from "react";
import {FaTrash} from "react-icons/fa6";
import Button from "../components/Button";

export default function TeamGenerator() {
  const [names, setNames] = useState<string[]>([]);
  const [nameToAdd, setNameToAdd] = useState<string>("");
  const [teamCount, setTeamCount] = useState<number>(2);
  const [teams, setTeams] = useState<string[][]>([]);

  function deleteName(index: number) {
    setNames(names.filter((name, i) => i !== index));
  }

  function addName() {
    setNames([...names, nameToAdd]);
    setNameToAdd("");
  }

  function generateTeams() {
    const k = teamCount < names.length ? teamCount : names.length
    const array = shuffleArray(names);
    setTeams(splitArray(array, k));
  }

  function splitArray(array: any[], k: number) {
    const partSize = Math.floor(array.length / k);
    const extra = array.length % k;
    const result = [];

    let start = 0;
    let end = 0;

    for (let i = 0; i < k; i++) {
      end = start + partSize + (i < extra ? 1 : 0);
      result.push(array.slice(start, end));
      start = end;
    }

    return result;
  }

  function shuffleArray(array: any[]) {
    const shuffledArray = [...array];
    return shuffledArray.sort(() => Math.random() - 0.5);
  }

  return (
    <div className="container">
      <h1>Random teams generator</h1>
      <div className="flex flex-row justify-evenly">
        <div className="mx-2 min-w-1/3">
          <div className="">
            <h2>Names</h2>
            <div className="my-1">
              <input className="mr-1" value={nameToAdd} onChange={(e) => setNameToAdd(e.target.value)}
                     type="text"/>
              <Button disabled={nameToAdd.length === 0}
                      onClick={() => addName()}>Add Name
              </Button>
            </div>
            {names.map((name, index) => (
              <div className="my-1 flex flex-row justify-between" key={name + index}>
                <span className="mr-1">
                  {name}
                </span>
                <Button variant={"danger"} onClick={() => deleteName(index)}>
                  <FaTrash/>
                </Button>
              </div>
            ))}
          </div>
        </div>

        <div className="mx-2 min-w-1/3">
          <h2>Teams</h2>
          <div>
            <input className="mr-1 w-8" value={teamCount}
                   onChange={(e) => setTeamCount(Number(e.target.value))} type="number"/>
            <Button disabled={names.length === 0}
                    onClick={() => generateTeams()}>Generate Teams
            </Button>
          </div>
          {teams.map((team, index) => (
            <div key={index}>
              <h3>Team {index + 1}</h3>
              {team.map((name, nameIndex) => (
                <div key={name + index}>{name}</div>
              ))}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
